### ISSUE TITLE
Can't flash image

### ISSUE THREAD

**Issue by ivybowman** [bishopdynamics/superbird-debian-kiosk#2]
Output below 
`ivy@carthinghost:~/superbird-tool $ sudo python3 superbird_tool.py --restore_device ../debian_v1.8_2024-01-03
Spotify Car Thing (superbird) toolkit, v0.1.0, by bishopdynamics
     https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Mode (buttons 1 & 4 held at boot)
Entering USB Burn Mode
writing images/superbird.bl2.encrypted.bin at 0xfffa0000
 writing to: 0xfffa0000
AMLC dataSize=16384, offset=65536, seq=0
[DONE]
AMLC dataSize=49152, offset=393216, seq=1
[DONE]
AMLC dataSize=16384, offset=229376, seq=2
[DONE]
AMLC dataSize=49152, offset=180224, seq=3
[DONE]
AMLC dataSize=16384, offset=65536, seq=4
[DONE]
AMLC dataSize=1224048, offset=81920, seq=5
[DONE]
[BL2 END]
Waiting for device...
Device is now in USB Burn Mode
 executing bulkcmd: "amlmmc part 1"
 Error (USBTimeoutError): bulkcmd timed out or failed!
 This can happen if the device ends up in a strange state, like as the result of a previously failed command
 Try power cycling the device by pulling the cable, and then boot up and try again
  You might need to do this multiple times
    If the device is connected through a USB hub, try connecting it directly to a port on your machine
ivy@carthinghost:~/superbird-tool $ sudo python3 superbird_tool.py --restore_device ../debian_v1.8_2024-01-03
Spotify Car Thing (superbird) toolkit, v0.1.0, by bishopdynamics
     https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Burn Mode (ready for commands)
restoring entire device from dumpfiles in ../debian_v1.8_2024-01-03
Wiping env partition
 executing bulkcmd: "amlmmc env"
  result: 
Bulkcmd failed: amlmmc env -> 
 Error (BulkcmdException): bulkcmd timed out or failed!
 This can happen if the device ends up in a strange state, like as the result of a previously failed command
 Try power cycling the device by pulling the cable, and then boot up and try again
  You might need to do this multiple times
    If the device is connected through a USB hub, try connecting it directly to a port on your machine
ivy@carthinghost:~/superbird-tool $ sudo python3 superbird_tool.py --restore_device ../debian_v1.8_2024-01-03
Spotify Car Thing (superbird) toolkit, v0.1.0, by bishopdynamics
     https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Mode (buttons 1 & 4 held at boot)
Entering USB Burn Mode
writing images/superbird.bl2.encrypted.bin at 0xfffa0000
 writing to: 0xfffa0000
AMLC dataSize=16384, offset=65536, seq=0
[DONE]
AMLC dataSize=49152, offset=393216, seq=1
[DONE]
AMLC dataSize=16384, offset=229376, seq=2
[DONE]
AMLC dataSize=49152, offset=180224, seq=3
[DONE]
AMLC dataSize=16384, offset=65536, seq=4
[DONE]
AMLC dataSize=1224048, offset=81920, seq=5
[DONE]
[BL2 END]
Waiting for device...
Device is now in USB Burn Mode
 executing bulkcmd: "amlmmc part 1"
  result: success
restoring entire device from dumpfiles in ../debian_v1.8_2024-01-03
Wiping env partition
 executing bulkcmd: "amlmmc env"
  result: success
 executing bulkcmd: "amlmmc erase env"
  result: success
initializing env subsystem
 executing bulkcmd: "amlmmc env"
  result: success
sending env (3358 bytes)
 writing to: 0x13000000
 executing bulkcmd: "env import -t 0x13000000 0xd1e"
  result: success
 executing bulkcmd: "env save"
  result: success
Validating size of partition: fip_a size: 0x400000 4MB - OK
writing partition: "fip_a" 0x42000+0x380000 from file: ../debian_v1.8_2024-01-03/fip_a.dump
chunk_size: 512.0KB, speed: 1.35MB/s progress: 88% remaining: 0MB / 4MB
Validating size of partition: fip_b size: 0x400000 4MB - OK
writing partition: "fip_b" 0x48000+0x380000 from file: ../debian_v1.8_2024-01-03/fip_b.dump
chunk_size: 512.0KB, speed: 1.36MB/s progress: 88% remaining: 0MB / 4MB
Validating size of partition: logo size: 0x800000 8MB - OK
writing partition: "logo" 0x4e000+0x780000 from file: ../debian_v1.8_2024-01-03/logo.dump
chunk_size: 512.0KB, speed: 1.56MB/s progress: 94% remaining: 0MB / 8MB
Validating size of partition: dtbo_a size: 0x400000 4MB - OK
writing partition: "dtbo_a" 0x56000+0x380000 from file: ../debian_v1.8_2024-01-03/dtbo_a.dump
chunk_size: 512.0KB, speed: 1.36MB/s progress: 88% remaining: 0MB / 4MB
Validating size of partition: dtbo_b size: 0x400000 4MB - OK
writing partition: "dtbo_b" 0x5c000+0x380000 from file: ../debian_v1.8_2024-01-03/dtbo_b.dump
chunk_size: 512.0KB, speed: 1.36MB/s progress: 88% remaining: 0MB / 4MB
Validating size of partition: vbmeta_a size: 0x100000 1MB - OK
writing partition: "vbmeta_a" 0x62000+0x0 from file: ../debian_v1.8_2024-01-03/vbmeta_a.dump
chunk_size: 1024.0KB, speed: 0MB/s progress: 0% remaining: 0MB / 1MB
Validating size of partition: vbmeta_b size: 0x100000 1MB - OK
writing partition: "vbmeta_b" 0x66800+0x0 from file: ../debian_v1.8_2024-01-03/vbmeta_b.dump
chunk_size: 1024.0KB, speed: 0MB/s progress: 0% remaining: 0MB / 1MB
Validating size of partition: boot_a size: 0x1000000 16MB - OK
writing partition: "boot_a" 0x6b000+0xf80000 from file: ../debian_v1.8_2024-01-03/boot_a.dump
chunk_size: 512.0KB, speed: 1.36MB/s progress: 97% remaining: 0MB / 16MB
Validating size of partition: boot_b size: 0x1000000 16MB - OK
writing partition: "boot_b" 0x77000+0xf80000 from file: ../debian_v1.8_2024-01-03/boot_b.dump
chunk_size: 512.0KB, speed: 1.36MB/s progress: 97% remaining: 0MB / 16MB
Validating size of partition: misc size: 0x800000 8MB - OK
writing partition: "misc" 0x28f0b0+0x780000 from file: ../debian_v1.8_2024-01-03/misc.dump
chunk_size: 512.0KB, speed: 1.36MB/s progress: 94% remaining: 0MB / 8MB
Validating size of partition: settings size: 0x10000000 256MB - OK
writing partition: "settings" 0x2970b0+0xff80000 from file: ../debian_v1.8_2024-01-03/settings.ext4
chunk_size: 512.0KB, speed: 1.36MB/s progress: 100% remaining: 0MB / 256MB
Validating size of partition: system_a size: 0x2040b000 516MB - OK
writing partition: "system_a" 0x83000+0x20400000 from file: ../debian_v1.8_2024-01-03/system_a.ext2
chunk_size: 44.0KB, speed: 1.36MB/s progress: 100% remaining: 0MB / 516MB
Validating size of partition: system_b size: 0x2040b000 516MB - OK
writing partition: "system_b" 0x189058+0x20400000 from file: ../debian_v1.8_2024-01-03/system_b.ext2
chunk_size: 44.0KB, speed: 1.35MB/s progress: 100% remaining: 0MB / 516MB
Validating size of partition: data size: 0x889ea000 2186MB - ...
Bulkcmd failed: amlmmc read data 0x13000000 0x889e9e00 0x200 -> failed:
 Error (BulkcmdException): bulkcmd timed out or failed!
 This can happen if the device ends up in a strange state, like as the result of a previously failed command
 Try power cycling the device by pulling the cable, and then boot up and try again
  You might need to do this multiple times
    If the device is connected through a USB hub, try connecting it directly to a port on your machine`

**Comment by ivybowman** [comment]
This results in what looks like a bootloop, although utility mode worked.

**Comment by ivybowman** [comment]
Appears to be when flashing the data partition.
<pre><font color="#26A269"><b>ivybowman@ivy-desktop</b></font>:<font color="#12488B"><b>~/superbird-tool</b></font>$ sudo python3 superbird_tool.py --restore_partition data ~/Downloads/debian_v1.8_2024-01-03/data.ext4 
Spotify Car Thing (superbird) toolkit, v0.1.0, by bishopdynamics
     https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Burn Mode (ready for commands)
Validating size of partition: data size: 0x889ea000 2186MB - ...
Bulkcmd failed: amlmmc read data 0x13000000 0x889e9e00 0x200 -&gt; failed:
 Error (BulkcmdException): bulkcmd timed out or failed!
 This can happen if the device ends up in a strange state, like as the result of a previously failed command
 Try power cycling the device by pulling the cable, and then boot up and try again
  You might need to do this multiple times
    If the device is connected through a USB hub, try connecting it directly to a port on your machine
<font color="#26A269"><b>ivybowman@ivy-desktop</b></font>:<font color="#12488B"><b>~/superbird-tool</b></font>$ 
</pre>

**Comment by ivybowman** [comment]
Full output of just data.
<pre><font color="#26A269"><b>ivybowman@ivy-desktop</b></font>:<font color="#12488B"><b>~/superbird-tool</b></font>$ sudo python3 superbird_tool.py --restore_partition data ~/Downloads/debian_v1.8_2024-01-03/data.ext4 
Spotify Car Thing (superbird) toolkit, v0.1.0, by bishopdynamics
     https://github.com/bishopdynamics/superbird-tool

Found device booted in USB Mode (buttons 1 &amp; 4 held at boot)
Entering USB Burn Mode
writing images/superbird.bl2.encrypted.bin at 0xfffa0000
 writing to: 0xfffa0000
AMLC dataSize=16384, offset=65536, seq=0
[DONE]
AMLC dataSize=49152, offset=393216, seq=1
[DONE]
AMLC dataSize=16384, offset=229376, seq=2
[DONE]
AMLC dataSize=49152, offset=180224, seq=3
[DONE]
AMLC dataSize=16384, offset=65536, seq=4
[DONE]
AMLC dataSize=1224048, offset=81920, seq=5
[DONE]
[BL2 END]
Waiting for device...
Device is now in USB Burn Mode
 executing bulkcmd: &quot;amlmmc part 1&quot;
 Error (USBTimeoutError): bulkcmd timed out or failed!
 This can happen if the device ends up in a strange state, like as the result of a previously failed command
 Try power cycling the device by pulling the cable, and then boot up and try again
  You might need to do this multiple times
    If the device is connected through a USB hub, try connecting it directly to a port on your machine
</pre>

**Comment by dturk0610** [comment]
I was just having a similar issue. Instead of running the --burn_mode or --enable_burn_mode, just simply running the restore image using the download seemed to work for me.

So I attempted a restore, which caused it to flash over the settings enabling burn mode, then unplugged, plugged back in while holding 1 & 4 buttons, then just ran the restore script again with the image and it seemed to take.

**Comment by ivybowman** [comment]
This for me was due to the wrong data partition size being used, I was able to flash after swapping size and size_alt in the partitions file.
